// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt4tZwwtkxPpULAHleGtuDnw5-98CrdiU',
    appId: '1:609073551752:web:75ec074aada852c576023d',
    messagingSenderId: '609073551752',
    projectId: 'focus-planner888',
    authDomain: 'focus-planner888.firebaseapp.com',
    storageBucket: 'focus-planner888.firebasestorage.app',
    measurementId: 'G-4ZDLXPTEWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwXr4n4UV3BixefFsF69RxB6WsiimSfT0',
    appId: '1:609073551752:android:49978177a7ed1c6c76023d',
    messagingSenderId: '609073551752',
    projectId: 'focus-planner888',
    storageBucket: 'focus-planner888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACZcif5mRAiKFo4hn2cVom9oJRTbO0diI',
    appId: '1:609073551752:ios:aec160e91772e2e676023d',
    messagingSenderId: '609073551752',
    projectId: 'focus-planner888',
    storageBucket: 'focus-planner888.firebasestorage.app',
    iosBundleId: 'com.example.focusPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACZcif5mRAiKFo4hn2cVom9oJRTbO0diI',
    appId: '1:609073551752:ios:aec160e91772e2e676023d',
    messagingSenderId: '609073551752',
    projectId: 'focus-planner888',
    storageBucket: 'focus-planner888.firebasestorage.app',
    iosBundleId: 'com.example.focusPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt4tZwwtkxPpULAHleGtuDnw5-98CrdiU',
    appId: '1:609073551752:web:01ede8ec27ae37be76023d',
    messagingSenderId: '609073551752',
    projectId: 'focus-planner888',
    authDomain: 'focus-planner888.firebaseapp.com',
    storageBucket: 'focus-planner888.firebasestorage.app',
    measurementId: 'G-L8872HDSV6',
  );
}
